src/main/urls.py
from django.urls import path
from . import views
from users import views as user_views
#from wkhtmltopdf.views import PDFTemplateView

#from .views import resume_template_choice

from main.pdf_views import download_pdf

from main.docx_views import  download_docx

urlpatterns = [
    

    #### Create CV ####
    path('my-cvs', views.my_cvs, name='my-cvs'),
    path('cv-preview/<int:pk>', views.cv_preview, name='cv_preview'),    
    path('cv/template-choice/<int:pk>/', views.change_template, name='change_template'),
    path('add-cv/', views.add_cv, name='add_cv'),    
    path('cv-done/<int:pk>/', views.cv_done, name='cv_done'),
    path('add-experience/<int:pk>/', views.work_experience, name='work_experience'),
    path('add-education/<int:pk>/', views.education, name='education'), 
    path('add-certifications/<int:pk>/', views.certifications, name='certifications'), 
    path('add-skills/<int:pk>/', views.skills, name='skills'), 
    path('add-languages/<int:pk>/', views.languages, name='languages'), 
    path('add-projects/<int:pk>/', views.projects, name='projects'), 
    path('add-hobbies/<int:pk>/', views.hobbies, name='hobbies'), 
    path('add-courses/<int:pk>/', views.courses, name='courses'), 
    path('add-publications/<int:pk>/', views.publications, name='publications'), 
    path('add-custom-section/<int:pk>/', views.custom_section, name='custom_section'), 

    
    
    #path('cv/pdf/<int:pk>/', views.GeneratePdf.as_view(), name='GeneratePdf'),
    #path('cv/pdf-test/<int:pk>/', views.cv_view_pdf, name='cv_view_pdf'),

    #path('cv/easypdf/<int:pk>', views.MyPDF.as_view(), name='MyPDF'),
    #path('cv/download/<int:pk>', views.pdf_download, name='pdf_download'),
    #path('cv/generate/<int:pk>/', views.cv_pdf, name='cv_pdf'), # avec le  service payant

    
    
    #path('cv/viewpdf/<int:pk>/', views.ViewPdf.as_view(), name='ViewPdf'), 
    
    #path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('cv/delete/<int:pk>/', views.delete_cv, name='delete-cv'),
    #path('cv/create/', views.CvWizard.as_view(views.FORMS), name='create-cv'),
    #path('cv/create/template', views.cv_template_choice, name='cv_template_choice'),
    #path('edit/cv/<int:pk>/', views.CvWizard.as_view(views.FORMS), name='edit-cv'),
    #path('edit/cv/<int:pk>/template', views.cv_template_choice, name='cv_template_choice'),
    #path('faq/', views.faq, name='faq'),
    #path('templates/', views.templates, name='templates'),
    #path('payment/', user_views.payment, name='payment'),
    #path('payment/notification/', user_views.payment_notification, name='payment-notif'),
    path('cv/<int:pk>/choose/', views.choose, name='choose'),
    path('cv/<int:pk>/view-cv/', views.choose, name='view-cv'),


    path('download/pdf/<int:pk>', download_pdf, name='download_pdf'),
    path('download/docx/<int:pk>', download_docx, name='download_docx'),


    
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cv/', include(('main.urls', 'main'), namespace='cv')),
    path('accounts/', include('allauth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/cv-forms/cv_certifications.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% block style%}
<style>

ul#id_cvs-sections li {
    list-style: none;
    width: calc(20% - 20px);
    height: 100px;
    margin: 5px;
    float: left;
    
}
ul#id_cvs-sections {
    width: 100%;
    float:left;
}
ul#id_cvs-sections li label{

    width: 100%;
    height: 100px;
    text-align: center;
    border-radius: 7px;
    background:#8282927a;
}
.cv-form-row p {
    width: 100%;
    float: left;
}
.form-row p input {
    width: 70%;
    padding: 5px;
    border-radius: 5px;
    border: 1px solid #f7ecf0;
}
.form-row p  {
    width: 50%;
    margin: 50px auto;
    text-align: center;
    margin-bottom: 30px;
}
.form-row p label  {
    display:none;
}
.tooltip {
    padding: 20px;
    opacity: 1;
}
input[type=radio] {
        display: none;
    }

label[for="id_cvs-sections_0"]:before {
    
    content: "\f0b1";
    font-family: FontAwesome;
    font-size: 50px;
    margin: 20px -20px;
    position: absolute; 
}

label[for="id_cvs-sections_1"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_1"]:checked+label {
    border: deeppink solid 4px;   
}
input#id_cvs-sections_1[type=checkbox]:checked+label {
    border: deeppink solid 4px;
}

label[for="id_cvs-sections_2"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
    
}
label[for="id_cvs-sections_3"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_4"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_5"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_6"]:before  {
    content: "\f0b1";
    font-family: "Fontawesome";
    
}
label[for="id_cvs-sections_7"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
    
}
label[for="id_cvs-sections_8"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_9"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_10"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
}

label[for="id_resumes-template_3"]  {
    background-image: url("{% static 'resumes/images/tokyo-resume-small.jpg' %}");
    border: lightslategray solid 1px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

label[for="id_resumes-template_4"]  {
    background-image: url("{% static 'resumes/images/rome-resume-small.jpg' %}");
    border: lightslategray solid 1px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

label[for="id_resumes-template_5"] {
    background-image: url("{% static 'resumes/images/sf-resume-small.jpg' %}");
    border: lightslategray solid 1px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

label[for="id_resumes-template_1"]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_1[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_2[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_3[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_4[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}
</style>


{% endblock %}
{% block title %}<title>Resume Name</title>{% endblock %}

{% block content %}



   
   
    
<div class="container cv" style="max-width:100%;">
    <div class="row cv">
        <div class="col-1 menu-cv" style="background:#d37f91;">
        <div class="cv-menu-icons">
            <i class="fa fa-file" aria-hidden="true"></i>
            <i class="fa fa-user" aria-hidden="true"></i>
            <i class="fa fa-save" aria-hidden="true"></i>
        </div>    
        </div>
        <div class="col-2 sections-cv" style="background:#818192;">
        <div class="cv-sections">                     
        
        <div class="cv-sections-buttons">
            <ul>
                <!-- <li><button name="wizard_goto_step" type="submit" value="resumes" class="active"><i class="fa fa-info-circle" aria-hidden="true"></i> Resume</button></li> -->
                {% if 'work_experience' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="work_experience"> <i class="fa fa-briefcase" aria-hidden="true"></i> Experience</button></li>                
                {% endif %}
                {% if 'education' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="education"><i class="fa fa-graduation-cap" aria-hidden="true"></i> Education</button></li>
                {% endif %}
                {% if 'certifications' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="certifications" class="active"><i class="fa fa-certificate" aria-hidden="true"></i> Certifications</button></li>
                {% endif %}
                {% if 'projects' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="projects"><i class="fa fa-tasks" aria-hidden="true"></i> Projects</button></li>
                {% endif %}
                {% if 'skills' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="skills"><i class="fa fa-star" aria-hidden="true"></i>  Skills</button></li>
                {% endif %}
                {% if 'languages' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="languages"><i class="fa fa-language" aria-hidden="true"></i> Languages</button></li>
                {% endif %}
                {% if 'publications' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="publications"><i class="fa fa-star" aria-hidden="true"></i>  Publications</button></li>
                {% endif %}
                {% if 'hobbies' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="hobbies"><i class="fa fa-language" aria-hidden="true"></i> Hobbies</button></li>
                {% endif %}
                {% if 'courses' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="courses"><i class="fa fa-language" aria-hidden="true"></i> Courses</button></li>
                {% endif %}
                {% if 'custom_section' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="custom_section"><i class="fa fa-language" aria-hidden="true"></i> Custom Section</button></li>
                {% endif %}
                
                <li><button name="success"><i class="fa fa-check" aria-hidden="true"></i> Done</button></li>
                
            </ul>
        </div>
        </div>
        
        </div>
        <div class="col-9 data" style="display:flex;">
            <div class="data-cv">
                <h2>Certifications</h2>
                <form action="" method="POST">{% csrf_token %}

                {{certification_formset.management_form}}
    
                   {%for form in certification_formset%}
                   <div class="cv-form-row form-duplicate">
                       <div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">      
                           <div class="card">
                               <div class="card-header" role="tab" id="heading{{forloop.counter}}">
                               <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapse{{forloop.counter}}"
                                   aria-expanded="false" aria-controls="collapse{{forloop.counter}}">
                                   <h5 class="mb-0">
                                   Certification
                                    <i class="fa fa-angle-down rotate-icon"></i>
                                   </h5>
                               </a>
                               </div>
    
                               <div id="collapse{{forloop.counter}}" class="collapse" role="tabpanel" aria-labelledby="heading{{forloop.counter}}" data-parent="#accordionEx">
                               <div class="card-body cv">
                                   
                                   {{form.as_p}}
                               </div>
                               </div>
    
                           </div>
                       </div>
                       
                   </div>
                    {% endfor %}
                   
                   <button type="submit" class="button-next">Next</button>
               </div>
            <div class="preview-cv">
                <div class="display-cv">
                <iframe src="/dashboard/cv/cv-preview/{{cv.id}}" class="cv-iframe-preview"></iframe></div>
            </div>
           
        </div>
        
    </div>
</div>
    
    </form>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        
        $(function() {
            $('.form-duplicate').formset({ 
                prefix: 'certification',
                added: function() {
                tinymceInit();
         }
         })
        })
    </script>


   
{% endblock %}

src/templates/cv-forms/cv_done.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% block style%}
<style>

ul#id_cvs-sections li {
    list-style: none;
    width: calc(20% - 20px);
    height: 100px;
    margin: 5px;
    float: left;
    
}
ul#id_cvs-sections {
    width: 100%;
    float:left;
}
ul#id_cvs-sections li label{

    width: 100%;
    height: 100px;
    text-align: center;
    border-radius: 7px;
    background:#8282927a;
}
.cv-form-row p {
    width: 100%;
    float: left;
}
.form-row p input {
    width: 70%;
    padding: 5px;
    border-radius: 5px;
    border: 1px solid #f7ecf0;
}
.form-row p  {
    width: 50%;
    margin: 50px auto;
    text-align: center;
    margin-bottom: 30px;
}
.form-row p label  {
    display:none;
}
.tooltip {
    padding: 20px;
    opacity: 1;
}
input[type=radio] {
        display: none;
    }

label[for="id_cvs-sections_0"]:before {
    
    content: "\f0b1";
    font-family: FontAwesome;
    font-size: 50px;
    margin: 20px -20px;
    position: absolute; 
}

label[for="id_cvs-sections_1"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_1"]:checked+label {
    border: deeppink solid 4px;   
}
input#id_cvs-sections_1[type=checkbox]:checked+label {
    border: deeppink solid 4px;
}

label[for="id_cvs-sections_2"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
    
}
label[for="id_cvs-sections_3"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_4"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_5"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_6"]:before  {
    content: "\f0b1";
    font-family: "Fontawesome";
    
}
label[for="id_cvs-sections_7"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
    
}
label[for="id_cvs-sections_8"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_9"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
    
}
label[for="id_cvs-sections_10"]  {
    background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
}

label[for="id_resumes-template_3"]  {
    background-image: url("{% static 'resumes/images/tokyo-resume-small.jpg' %}");
    border: lightslategray solid 1px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

label[for="id_resumes-template_4"]  {
    background-image: url("{% static 'resumes/images/rome-resume-small.jpg' %}");
    border: lightslategray solid 1px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

label[for="id_resumes-template_5"] {
    background-image: url("{% static 'resumes/images/sf-resume-small.jpg' %}");
    border: lightslategray solid 1px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

label[for="id_resumes-template_1"]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_1[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_2[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_3[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}

input#id_resume_template_4[type=radio]:checked+label {
    border: deeppink solid 4px;
    height: 253px;
    width: 223px;
    display: inline-block;
    margin: 1.5em;
}
</style>


{% endblock %}
{% block title %}<title>Education</title>{% endblock %}

{% block content %}



   
    
    
<div class="container cv" style="max-width:100%;">
    <div class="row cv">
        <div class="col-1 menu-cv" style="background:#d37f91;">
        <div class="cv-menu-icons">
            <i class="fa fa-file" aria-hidden="true"></i>
            <i class="fa fa-user" aria-hidden="true"></i>
            <i class="fa fa-save" aria-hidden="true"></i>
        </div>    
        </div>
        <div class="col-2 sections-cv" style="background:#818192;">
        <div class="cv-sections">                     
       
        <div class="cv-sections-buttons">
            <ul>
                <!-- <li><button name="wizard_goto_step" type="submit" value="resumes" class="active"><i class="fa fa-info-circle" aria-hidden="true"></i> Resume</button></li> -->
                {% if 'work_experience' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="work_experience"> <i class="fa fa-briefcase" aria-hidden="true"></i> Experience</button></li>                
                {% endif %}
                {% if 'education' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="education" class="active"><i class="fa fa-graduation-cap" aria-hidden="true"></i> Education</button></li>
                {% endif %}
                {% if 'certifications' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="certifications"><i class="fa fa-certificate" aria-hidden="true"></i> Certifications</button></li>
                {% endif %}
                {% if 'projects' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="projects"><i class="fa fa-tasks" aria-hidden="true"></i> Projects</button></li>
                {% endif %}
                {% if 'skills' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="skills"><i class="fa fa-star" aria-hidden="true"></i>  Skills</button></li>
                {% endif %}
                {% if 'languages' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="languages"><i class="fa fa-language" aria-hidden="true"></i> Languages</button></li>
                {% endif %}
                {% if 'publications' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="publications"><i class="fa fa-star" aria-hidden="true"></i>  Publications</button></li>
                {% endif %}
                {% if 'hobbies' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="hobbies"><i class="fa fa-language" aria-hidden="true"></i> Hobbies</button></li>
                {% endif %}
                {% if 'courses' in cv.sections %}
                <li><button name="wizard_goto_step" type="submit" value="courses"><i class="fa fa-language" aria-hidden="true"></i> Courses</button></li>
                {% endif %}
                
                <li><button name="success"><i class="fa fa-check" aria-hidden="true"></i> Done</button></li>
                
            </ul>
        </div>
    
        </div>
        
        </div>
        <div class="col-9 data" style="display:flex;">
             <div class="data-cv">
             
             <form action="" method="POST">{% csrf_token %}
             
                
                <div class="cv-form-row form-duplicate">
                    <div class="congrats">
                    <i class="fa fa-check" aria-hidden="true"></i>
                    <h4>Your Cv Has Been Successfuly Created!</h4>
                </div>
                <div class="done-page-download">
                    <div class="done-download-button pdf"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> 
                    <a href="{% url 'cv:download_pdf' pk=cv.pk %}">
                        Download PDF
                    </a> </div>
                    <div class="done-download-button docx"><i class="fa fa-file-word-o" aria-hidden="true"></i>                     <a href="{% url 'cv:download_docx' pk=cv.pk %}">
                        Download DOC
                    </a> </div>
                    <div class="done-download-button google"><i class="fa fa-google" aria-hidden="true"></i>Save To Google Drive</div>
                    <div class="done-download-button drop"><i class="fa fa-dropbox" aria-hidden="true"></i>Save To DropBox</div>
                    <div class="done-download-button email"><i class="fa fa-envelope" aria-hidden="true"></i>Send To Email</div>
                </div>
                </div>
                 
                
                <button type="submit" class="button-next">Next</button>
            </div>
            <div class="preview-cv">
                <iframe data-enlargeable src="/dashboard/cv/cv-preview/{{cv.id}}" class="cv-iframe" style="border:0 #fffff none;" scrolling="no" frameborder="1" marginhright="0px" marginwidth="0px" height="100%" width="100%" allowfullscreen></iframe>
                <span >Preview</span>
            </div>
            
          
        </div>
        
    </div>
</div>
    
    </form>
{% endblock %}
{% block script %}
    
{% endblock %}